app = "mondtype"
primary_region = "sin"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]